### ISSUE TITLE
User Profile( Meta Data ) Is Not Saved

### ISSUE THREAD

**Issue by bhushanjawle** [piklist/piklist#13]
### Details

Piklist Version:  0.9.9.12 & 0.9.9.13
PHP Version: 7.0.18

Server OS: Ubuntu 16.04

### What was expected to happen
Save user meta information.

### What happened instead
No meta data saved in database.

### Steps to reproduce this

- Create a file in custom-plugin/parts/users/myusermeta.php

- Add following code
 ```php
<?php
/*
Title: Postal Information
*/

piklist('field', array(
    'type' => 'text'
    ,'field' => 'user_address'
    ,'label' => 'Address'
    ,'attributes' => array(
      'class' => 'text'
    )
  ));
?>
```

- Go to 'Edit My Profile' under default user menu
- Enter test data in displayed address text field and click save
- It is expected that data is saved however it isn't (cross verified with usermeta table, data was not saved)

**Comment by bhushanjawle** [comment]
I found a way around it, not sure if this the right way to do it though.
I am able to save the above address field by adding `'scope'=>'user_meta'` in above field.

@sbruner can you please confirm if this is the right way of using it ?

**Comment by sbruner** [comment]
`'scope'=>'user_meta'` is fine, but shouldn't be needed in the admin, only for front end forms.   Does user meta work with the Piklist Demos?  If you turn on demos, edit your profile and save some data. Does that work?

**Comment by JasonTheAdams** [comment]
I just tested this on 0.10 Beta 2 and I'm not having any issues with the Piklist demo code which omits the `'scope' => 'user_meta'`, which shouldn't be necessary as it's assumed from context.

Did you delete the piklist plugin entirely and then add the beta? Some users have been overwriting the contents of the old plugin with the new, but that isn't enough.

**Comment by bhushanjawle** [comment]
Hi @sbruner, yes was able user meta did work with demo.
@JasonTheAdams I overwrote it and I do see some inconsistent behaviour. Will delete it re-install it and report my findings with clean beta 2 installation

**Comment by JasonTheAdams** [comment]
@bhushanjawle I just made a note in the Piklist forums for this. If you simply overwrite then there are files that get left that shouldn't be there and cause issues. It's necessary to replace the plugin directory entirely.

**Comment by JasonTheAdams** [comment]
@bhushanjawle Did the issue get resolved when you swapped out piklist versions?

**Comment by bhushanjawle** [comment]
@JasonTheAdams just rechecked on separate install by physically deleting the earlier plugin and installing 0.10 by git.
It worked as expected, i.e. without `'scope' => 'user_meta'` .
Thank you for your help @JasonTheAdams @sbruner

**Comment by JasonTheAdams** [comment]
Glad to hear! Closing this issue, then. :)
