### ISSUE TITLE
Default Value on field not working when used in nested group with addmore 

### ISSUE THREAD

**Issue by beatelite** [piklist/piklist#15]
### Details

Piklist Version: 
beta 10

PHP Version:
5
Server OS:
Ubuntu

### What was expected to happen
When using value attribute in nested groups, I expected the value to show up

### What happened instead
nothing showed up

### Steps to reproduce this
create a group, create with an add more. 
Then create a field and give it a value 

example with code omitted for brevity:

          `        ,array(
            'type' => 'group'
            ,'label' => __('Add more', 'piklist-demo')
            ,'description' => __('Start adding.', 'piklist-demo')
            ,'field' => 'events'
            ,'value' => 'none'
            ,'add_more' => true
            ,'fields' => 
                array(
                    array(
                	   'type'		=> 'text'
                    	,'field'		=> 'type'
                    	,'label'		=> __('')
                    	,'value'     => 'Event' // This is not working
                        ,'attributes' => array(
                            'class' => 'small-text'
                            ,'readonly' => 'readonly'
                        )
                    ), 
etc..
`

**Comment by cjwd** [comment]
This is also not working in Piklist 0.9.9.12

**Comment by sbruner** [comment]
@beatelite-- This is currently working in the latest release:
https://github.com/piklist/piklist/releases

Expected behavior is to show the default value on the first add_more.
