### ISSUE TITLE
Terms metabox: "New" defaults to false

### ISSUE THREAD

**Issue by donnamcmaster** [piklist/piklist#19]
### Details
Created a Piklist file in parts/terms. The meta box didn't show up when I went to create a new term. Documentation says that "New" defaults to true. I added the line "New: true" to the comment block at the top of the file, and now the meta box is displayed. 

Piklist Version: 0.10 Beta 2

PHP Version: 5.6.30

Server OS: Mac OS 10.10.5

### What was expected to happen
The file I placed in parts/terms had this header: 
```
/*
Title: Media Credit Details
Description: 
Taxonomy: media_credit
*/
```
I expected my meta box to show up when I went to the taxonomy edit page to create a new term. 

### What happened instead
The meta box didn't appear. So I added a line: 
```
/*
Title: Media Credit Details
Description: 
Taxonomy: media_credit
New: true
*/
```
and then reloaded the taxonomy edit page and the meta box appeared. 

### Steps to reproduce this
Create a terms meta box file without "New: true" in the comment header. 

Sorry, no time to try to track it down right now. I'll look at the Piklist code later today if I can. 
-- Donna

**Comment by donnamcmaster** [comment]
Addendum: I just ran into the opposite problem! I had New:true set, added the term, but when I went to edit it the edit fields were missing. This time, taking New:true out of the header made the meta-box reappear. I'm really confused now. :-o

**Comment by JasonTheAdams** [comment]
I played around with this the other day. I'm trying to figure out what makes the most sense, regardless of what the docs say. Also, is there any difference between when the `New: true` was required and wasn't? That's puzzling! Hahah!

**Comment by sbruner** [comment]
@donnamcmaster -- I just tested and this now works as expected.  Default is "false".  Set:
`new: true`, to show your fields when creating a new term.

Docs have been updated: https://docs.piklist.com/comment-block-parameters/#new

cc @JasonTheAdams
