### ISSUE TITLE
Warnings when using shortcode with no arguments

### ISSUE THREAD

**Issue by hakakou** [piklist/piklist#20]
When using a shortcode with NO parameteres, I get warning in the generated output (see below)

Example: [child-navigation]

The problem is fixed if I add manually any param, for example:

[child-navigation dumb="1"]

### Details

Piklist Version: 1 beta 

PHP Version: 7.1

Server OS: Server OS: Windows & IIS 7

### What happened instead
Saw the following messages in the generated page output
Warning: Illegal string offset 'content' in C:\WP\wp-content\plugins\piklist\includes\class-piklist-shortcode.php on line 255

Warning: Cannot assign an empty string to a string offset in C:\WP\wp-content\plugins\piklist\includes\class-piklist-shortcode.php on line 255

**Comment by kevinpmiller** [comment]
Great catch! We will get this addressed asap and added to our unit tests.

**Comment by sbruner** [comment]
@hakakou--  I know it's been a while, but I believe this is fixed.  Can you test with our latest release?
https://github.com/piklist/piklist/releases

**Comment by hakakou** [comment]
Yes, tested on 0.10 Beta 3 with Windows & IIS 7.  
No problem.

**Comment by sbruner** [comment]
Great closing ticket!
