### ISSUE TITLE
Shortcode containing grouped fields does not serialize data

### ISSUE THREAD

**Issue by hakakou** [piklist/piklist#26]
### Details

Piklist Version: 0.10 Beta 2

PHP Version: 7.1

Server OS: Windows IIS7

### What was expected to happen

When inserting a short code that contains a group with fields, all values should be serialized in the shortcode with some method, and also should be able to allow further modification by clicking the edit shortcut again.

### What happened instead

Shortcode shows weird values and does not work either in the code, or by editing again.

### Steps to reproduce this

Using a shortcode with the following fields:

```
<?php
/*
Name: Icon
shortcode: icon
icon: dashicons-layout
preview: true
*/

piklist('field', array(
'type' => 'group'
,'field' => 'group1'
,'label' => 'Group 1'
,'fields' => array(
  array(
	'type' => 'text'
	,'label' => 'Address 1'
	,'field' => 'address_1'
  )
  ,array(
	'type' => 'text'
	,'label' => 'Address 2'
	,'field' => 'address_2'
  )
)
));  
```

Enter in the fields A and B.

The shortcode produced is
```
[icon group1="B"]
```
And of course the fields are empty if you try to edit again

**Comment by JasonTheAdams** [comment]
Thanks for reporting this! I'm quite sure this is related to #24 so I'm going to mark this as a duplicate and close it.

**Comment by hakakou** [comment]
I don't think it's a duplicate unless you know for sure the deeper reason for this :-)

I am saying this because this problem I am reporting happens even with simple ASCII strings (even without spaces and unicode characters).

**Comment by JasonTheAdams** [comment]
I referenced this in the other issues, so we'll be able to check this as well. But there's a serialization issue in the JS code which I haven't quite been able to find yet. I asked the team member who wrote that code to take a look.
