### ISSUE TITLE
add-more field doesn't work with post-relate field

### ISSUE THREAD

**Issue by strarsis** [piklist/piklist#28]
@sbruner , @kevinpmiller , @JasonTheAdams :

### Details

Piklist Version: 0.9.9.12

PHP Version: 7.1

Server OS: Ubuntu 16.04 LTS

### What was expected to happen
post-relate field is included in each add-more field item

### What happened instead
Only one post-relate field is shown below the add-more field items

### Steps to reproduce this
```php
/*
Title: Test
Post Type: parent-post
*/

piklist('field', array(
  'type' => 'group'
  ,'field' => 'items'
  ,'label' => 'Items'
  ,'add_more' => true
  ,'fields' => array(
    array(
      'type' => 'text'
      ,'field' => 'field-1'
      ,'label' => 'Field 1'
      ,'value' => ''
    )
    ,array(
      'type' => 'post-relate'
      ,'scope' => 'post'
      ,'template' => 'field'
    )
  )
));
````
![screenshot](https://cloud.githubusercontent.com/assets/9271436/26387143/8498bc0c-404b-11e7-8de9-58312d597302.png)

Related discussion thread on piklist website: https://piklist.com/support/topic/add_more-and/

**Comment by JasonTheAdams** [comment]
We recommend checking out the [new way of creating relate fields](https://docs.piklist.com/tutorials/relationships/working-with-field-relationships/), wherein most fields can be "converted" into a relate field. The `post-relate` field is being phased out in favor of this.
