### ISSUE TITLE
Better Docs at the website

### ISSUE THREAD

**Issue by bicho44** [piklist/piklist#3]
### Details
Version of Piklist: any
The docs are laking some step by step guides, or videos
The *tabs system* is so complicated to make it work, every time i try to do some tabs a pain in my chest threat my hart to explode, lol :rofl: 
The last version of the docs are really convoluted i think a docs like [Bootstrap](http://getbootstrap.com/) / [Less,](http://lesscss.org/) etc are more easy to understand

Just an idea

**Comment by JasonTheAdams** [comment]
@bicho44 Just wanted to let you know that this is definitely on our radar. We're looking into options now. We really want to take our documentation to the next level and make it possible for folks to contribute.

**Comment by proweb** [comment]
yeah, just today tried to find how to limit nubber of files picked in Media manager for field `upload_media` and stuck with it in docs =(

**Comment by sbruner** [comment]
New Docs are live!
https://docs.piklist.com/
