### ISSUE TITLE
Radio fields are being stored as having multiple values when there can be only one

### ISSUE THREAD

**Issue by JasonTheAdams** [piklist/piklist#32]
### Details

Piklist Version: 0.10 Beta 2

### What was expected to happen
Radio fields should store a single value as the user can only select one value

### What happened instead
It's stored in an array like a checklist, so to get the value for a field called `radio_test` would be `get_post_meta($id, 'radio_test', true)[0]`

### Steps to reproduce this
1. Create a radio field
2. Store some value via that radio field
3. Check how it's stored in the database

**Comment by sbruner** [comment]
@JasonTheAdams -- Please test. I believe this is fixed.  Here's what I see in the db.
<img width="818" alt="screenshot 2018-04-06 23 32 05" src="https://user-images.githubusercontent.com/154488/38450825-bf0e59f4-39f2-11e8-8e5c-4f1fdbde37e1.png">

**Comment by JasonTheAdams** [comment]
Does appear to be working! Yay!
