### ISSUE TITLE
Database corruption of post_meta values on post revision

### ISSUE THREAD

**Issue by hughc** [piklist/piklist#34]
### Details

Piklist Version: 0.10b2

PHP Version: 5.6.19

Server OS: XAMPP under Win10, issue noted under Centos cPanel hosting also

Database level corruption of metadata values.

Clean Wordpress 4.8 (witnessed under earlier version also). Only plugins are Piklist, The Events Calendar.

#### Test 1: Piklist disabled, The Events Calendar enabled.
Create events, edit events. All good. Database values for event metadata in postmeta table are correctly serialized arrays, ie for the key `_tribe_modified_fields`:

```
a:17:{s:12:"_EventOrigin";d:1497373618;s:10:"_edit_last";d:1497373623;s:10:"post_title";d:1497373624;s:11:"post_status";d:1497373624;s:17:"_EventShowMapLink";d:1497373624;s:13:"_EventShowMap";d:1497373624;s:15:"_EventStartDate";d:1497373624;s:13:"_EventEndDate";d:1497373624;s:18:"_EventStartDateUTC";d:1497373624;s:16:"_EventEndDateUTC";d:1497373624;s:14:"_EventDuration";d:1497373624;s:20:"_EventCurrencySymbol";d:1497373624;s:22:"_EventCurrencyPosition";d:1497373624;s:10:"_EventCost";d:1497373624;s:9:"_EventURL";d:1497373624;s:14:"_EventTimezone";d:1497373624;s:18:"_EventTimezoneAbbr";d:1497373624;}
```

#### Test 2: Enable Piklist. Edit an existing event. Re-examine database. 
New meta values, associated with next post revision, for same `meta_key` are now Strings, not Arrays:
```
s:633:"a:18:{s:12:"_EventOrigin";d:1497373618;s:10:"_edit_last";d:1497373623;s:10:"post_title";d:1497373624;s:11:"post_status";d:1497373624;s:17:"_EventShowMapLink";d:1497373624;s:13:"_EventShowMap";d:1497373624;s:15:"_EventStartDate";d:1497373652;s:13:"_EventEndDate";d:1497373652;s:18:"_EventStartDateUTC";d:1497373652;s:16:"_EventEndDateUTC";d:1497373624;s:14:"_EventDuration";d:1497373652;s:20:"_EventCurrencySymbol";d:1497373624;s:22:"_EventCurrencyPosition";d:1497373624;s:10:"_EventCost";d:1497373624;s:9:"_EventURL";d:1497373624;s:14:"_EventTimezone";d:1497373624;s:18:"_EventTimezoneAbbr";d:1497373624;s:8:"post_tag";i:1497337652;}";
```

Somehow, the Events Manager doesn't seem to care about this particular `meta_key` as it seems to tolerate its corruption. Enabling the Pro version of the plugin, and then attempting to edit a existing event dies with a catchable fatal error as,when handling event repeat meta value (repeat event schedules are a Pro feature) it has pulled a string from the database where it was expecting an array, because Piklist has corrupted the data at the database level. I've seen other values, written by other plugins, corrupted in a similar manner.

#### Test 3: Clean install again; EV and Piklist enabled.
Following change to Piklist code:

The issue appears to occur because Piklist pulls a value from the database using a raw SQL query, and then writes the value using a standard method, causing the read array to be written back as a string. 

This one-liner change to the code, in `includes/class-piklist-revision.php` on line 56:

          $object->meta_value = maybe_unserialize($object->meta_value);
          add_metadata('post', $post_id, $object->meta_key, $object->meta_value);

Is enough to keep the database clean. As revisions are created, the `_tribe_modified_fields` values remain as arrays across revisions, as expected.

**Comment by JasonTheAdams** [comment]
Good catch, @hughc! Thank you for doing the extra work to clarify what the exact issue is. This inspired an idea for #35. Please check out that pull request, test it out, and let me know if that solves your issue.

**Comment by hughc** [comment]
That seems to have done the trick @JasonTheAdams - db remains clean across revisions now.

Raw data in, raw data out makes more sense than raw data from the db, Wordpress-sanitised data back out to the db when transcribing values. Fixing it with a single query is pretty nice too!

Quite surprised no-one else had turned this one up. It's pretty nasty, as it can leave your db in an unusable state, and it's certainly not Events Manager specific.

**Comment by JasonTheAdams** [comment]
@hughc To be honest I'm surprised as well. I suspect people don't revert to previous revisions terribly often. Thank you for reporting this though, as I believe we not only fixed a bug but also found an opportunity to increase performance for high-meta posts.

**Comment by JasonTheAdams** [comment]
Hmm... I guess that means that what's being displayed on the post page after updating is not he post itself, but the most recent revision. Interesting!
