### ISSUE TITLE
Suggestion: a filter to change some of the post_type_labels

### ISSUE THREAD

**Issue by cjwd** [piklist/piklist#45]
Hi,
The convenience of the piklist('post_type_labels', 'post_type_name') is great. However, there are times I just want customise a couple of the label but still use the convenience function usually all_items and add_new_item.

I checked the function to see if there is apply_filters on the array to override some of the labels but didn't see any. It would be great to add a filter for the returned array. Currently I use array_merge but this could be useful for post types of piklist plugins you didn't author.

**Comment by JasonTheAdams** [comment]
Hi @cjwd!

Thanks for the idea!

I think there's a simpler solution here than adding another hook. Here's a couple of options:

1. Use a variable and then change the labels before applying them to the post type:
```php
$labels = piklist('post_type_labels', 'Project');

$labels['menu_name'] = 'Active Projects';

// Register post type with $labels
```

2. If for some reason you do need to change the labels down the line, then use the `post_type_labels_{$post_type}` hook: https://developer.wordpress.org/reference/hooks/post_type_labels_post_type/

Hope this helps!

**Comment by cjwd** [comment]
Thanks for the tip.
