### ISSUE TITLE
post_type_labels for "Research"

### ISSUE THREAD

**Issue by sbruner** [piklist/piklist#46]
### Details

Piklist Version: 0.10

### What was expected to happen

Used post_type_labels() for the CPT "Research". Menu says "All Researches".

### What happened instead
Should have said "All Research"

### Steps to reproduce this

Create a new CPT, and use this line:
`  'labels' => piklist('post_type_labels', 'Research')`

**Comment by hughc** [comment]
I struck this recently, I had a binary Taxonomy labelled `Available in Australia`, to simply classify local availability for products...  I started seeing the singular form: `Available in Australium`
:-|

**Comment by JasonTheAdams** [comment]
I don't think we should fix this, actually. The labeling function is not and cannot be infallible. There are so many exceptions within languages for plural forms that it's impractical to try and match them all as it would make the function ridiculously large and slow.

If a label doesn't work, then enter the labels manually as one would normally do when registering a post type. For a list of available labels please see the [get_post_type_labels docs](https://developer.wordpress.org/reference/functions/get_post_type_labels/).

@sbruner Feel free to reopen this if you feel it's in error. But `Research` is a perfect example of an exception, as the plural of Church is Churches and Couch is Couches.
