### ISSUE TITLE
post_updated_messages not working as expected

### ISSUE THREAD

**Issue by manutiedra** [piklist/piklist#53]
For CPT, when you update it in the backend, the preview link in the notice should only be added if publicly_queryable is true

Piklist Version: 0.10

PHP Version: 7.1.12

Server OS: Windows 2016 Server

### What was expected to happen

In WP core, in edit-form-advanced.php, they add the preview links acccording to:

$viewable = is_post_type_viewable( $post_type_object );

and is_post_type_viewable basically checks publicly_queryable

so if I have a CPT callled MyCPT with publicly_queryable = false and I save it as a draft the notice will be:
"MyCPT draft updated"

### What happened instead

Now it shows "MyCPT draft updated. Preview MyCPT"

### Steps to reproduce this

Create a CPT with publicly_queryable = false and save it.

### How to fix it

in class-piklist-cpt.php the method post_updated_messages_filter needs to be changed. It should check the publicly_queryable before and add the preview links if it is true.

**Comment by JasonTheAdams** [comment]
Hi @manutiedra!

Thanks for pointing this out! Since you've already tracked all this down, any interest in creating a PR for it? We'd love to have more contributors and you're 90% there.

**Comment by manutiedra** [comment]
Hi @JasonTheAdams, 

will try to do it this weekend. 

Best regards.

**Comment by manutiedra** [comment]
PR created. I hope to see the changes merged soon.

Best regards,
Manu

**Comment by JasonTheAdams** [comment]
PR has been merged. Thanks for contributing!

**Comment by manutiedra** [comment]
Great! Thank you for your help and interest to get it done.
