### ISSUE TITLE
Custom post status "leaking" out to other post_types

### ISSUE THREAD

**Issue by emersonthis** [piklist/piklist#69]
### Details
WP Version: 
4.9.3

Piklist Version:
0.9.9.13

PHP Version:
7.1.7

Server OS:
Ubuntu (I'm pretty sure)

### What was expected to happen
Posts with status `future` should not appear in the main loop by default.

### What happened instead
A custom post_type registered with Piklist caused normal posts with status `future` to start appearing in the main loop.

### Steps to reproduce this

The following code behaves as expected. But if you uncomment the final lines to include that status configurations, normal posts scheduled for the future start appearing in the main loop.

```
add_filter('piklist_post_types', 'deutsch_post_types');
function deutsch_post_types($post_types)
{
  $post_types['location'] = array(
    'labels' => piklist('post_type_labels', 'Location')
    ,'title' => __('Enter a location title')
    ,'menu_icon' => get_bloginfo('template_directory') . '/images/locations-menu-icon.svg'
    ,'page_icon' => get_bloginfo('template_directory') . '/images/locations-menu-icon.png'
    ,'supports' => array(
      'title',
    )
    ,'public' => true
    ,'admin_body_class' => array(
      'custom-body-class'
    )
    ,'has_archive' => false
    ,'rewrite' => array(
      'slug' => 'location'
    )
    ,'capability_type' => 'post'
    ,'edit_columns' => array(
      'title' => __('Location')
    )
    ,'hide_meta_box' => array(
      'author'
    )
    // ,'status' => array(
    //   'current' => array(
    //     'label' => 'Current'
    //     ,'public' => true
    //   )
    //   ,'future' => array(
    //     'label' => 'Future'
    //     // ,'public' => true
    //   )
    // )
  );
...
```

**Comment by sbruner** [comment]
@kevinpmiller @JasonTheAdams -- This is happening because the default args Piklist sets for post_status is different than WordPress.

Piklist: https://github.com/piklist/piklist/blob/develop/includes/class-piklist-cpt.php#L196-L211

WordPress: https://build.trac.wordpress.org/browser/tags/4.9.5/wp-includes/post.php#L783

We would need to change the following parameters from `true` to `null` to match WordPress.

This might be a breaking change for those that use custom post statuses and didn't set these values due to the defaults.

Thoughts?

```
'public' => null
,'protected' => null
,'show_in_admin_status_list' => null
,'show_in_admin_all_list' => null
```

**Comment by JasonTheAdams** [comment]
@sbruner Interesting. So have you tested changing those to null? That fixes the issue?

Why do we need to include all those defaults to begin with? Core obviously handles the default when the post type is registered. I feel like it would be best to let WordPress handle the defaults and have Piklist only be concerned with additional parameters — i.e. statuses.

**Comment by sbruner** [comment]
@kevinpmiller  @JasonTheAdams 

I suggest we use the WordPress defaults for register_post_status when registering custom statuses in Piklist. EXCEPT 'show_in_admin_status_list'. WordPress sets this to null by default, and we currently have it set to true:
https://build.trac.wordpress.org/browser/tags/4.9.5/wp-includes/post.php#L792

If we go with the WordPress default of null, posts may disappear from list tables around the world for users that did not use that parameter when registering their custom statuses. Leaving this for backwards compatibility.

 I created a PR for this. Let me know what you think:
https://github.com/piklist/piklist/pull/79

**Comment by sbruner** [comment]
This has been fixed in:
https://github.com/piklist/piklist/pull/79

Available here:
https://github.com/piklist/piklist/releases/tag/0.10-beta.3

**Comment by sbruner** [comment]
@kevinpmiller @JasonTheAdams -- so it seems that reverting to WordPress defaults is causing some issues. By default, post statuses or NOT PUBLIC, so we're causing 404's.

Thoughts on:
`'public' => true`

?

**Comment by sbruner** [comment]
added to v0.11.2
