### ISSUE TITLE
Settings page is not tabbed

### ISSUE THREAD

**Issue by panayotov** [piklist/piklist#72]
### Details
I replaced the latest stable piklist ( 0.9.9.13 ) with the master branch ( 0.10 ). I noticed some different behaviour on multiple places, solely by the piklist version. 

Piklist Version:
0.10

PHP Version:
5.x - 7.x

Server OS:

### What was expected to happen
When creating a setting page with tabs, each tab is displayed in tab ( single_line => false )

### What happened instead
All the settings were on the same pages, no tabs

### Steps to reproduce this
Replace the piklist plugin from stable to beta.

**Comment by sbruner** [comment]
Thank you for reporting this issue.

If you activate Piklist Demos, and go to he demos settings page do you see tabs?
<img width="1092" alt="screenshot 2018-02-27 10 16 39" src="https://user-images.githubusercontent.com/154488/36736766-671869ce-1ba7-11e8-8a9f-4936940dfc06.png">

**Comment by panayotov** [comment]
Not, when using the 0.10 with enabled piklist demos, the demos tabs seems to be fine.
On my case I did not added any workflow, but the settings were still tabbed;

Here is my code:

```
 $pages[] = array(
   'page_title' => __('LC Settings', 'lc'),
   'menu_title' => __('LC Settings', 'lc'),
   'capability' => 'manage_options',
   'menu_slug' => 'lc_settings',
   'setting' => 'lc_settings',
   'menu_icon' => get_template_directory_uri() . '/inc/admin/logo.png',
   'page_icon' => get_template_directory_uri() . '/inc/admin/logo.png',
   'single_line' => false,
   'default_tab' => 'Partials',
   'save_text' => 'Save Settings'
  );
```
When clicking on other tab and see the slug, it has some workflow applied 

`wp-admin/admin.php?page=lc_settings&_%5Bflow%5D=lc_settings&_%5Bflow_page%5D=footer`

**Comment by sbruner** [comment]
@panayotov-- Since the demos are working, I'm going to close this ticket.  Feel free to post your workflow code in full over at Piklist support and we'll help you debug it:
https://piklist.com/support/forum/piklist/
