### ISSUE TITLE
Relate: create new post not creating new post

### ISSUE THREAD

**Issue by sbruner** [piklist/piklist#78]
### Details

Piklist Version: 0.10

PHP Version: tested with 5.6 and 7.2

### What was expected to happen
-add new Demo
-Goto "Relate" tab and "advanced" subtab
-Under "Related Posts" create a new post
-A new post would be created

### What happened instead
-no post was created.

**Comment by JasonTheAdams** [comment]
@sbruner I'm seeing more of the `count()` warnings that were dealt with in #77. I'm reluctant to just add more structural checking with `isset` and such as I don't know if there's a bigger issue upstream. @kevinpmiller is the best person for this as it seems to be an issue in the `Piklist_Form` class. This isn't an issue with how the relate code works.

At some point down the road it would be a really good idea to break apart the `Piklist_Form` class as it's a [god object](https://en.wikipedia.org/wiki/God_object) and difficult to debug. Not in the scope of this issue, however, just something to keep in mind.

**Comment by kevinpmiller** [comment]
@sbruner 

I think this is an enhancement? The original post hasn't been created yet so it can be in a relationship.

Some thoughts:

- Force the creation of the original post on a post being created for a relationship.
- Disable the ability to relate if there is no post object present.
- Add a validation message to the field checking for a post object.

@JasonTheAdams 
I agree on breaking up the class, the core piklist class may need it as well.

**Comment by sbruner** [comment]
@kevinpmiller -- This is not an enhancement. The way it works now:
-add new Demo
-Goto "Relate" tab and "advanced" subtab
-Under "Related Posts" create a new post
-A new post would be created
-The relationship is created.

The new post is not created, and obviously neither is the relationship.

**Comment by sbruner** [comment]
Fixed: https://github.com/piklist/piklist/commit/189cf4d5c4f724b117037bba4bae4ccb31c1c2c1
