### ISSUE TITLE
Piklist database update doesn't terminate

### ISSUE THREAD

**Issue by donnamcmaster** [piklist/piklist#81]
### Details

Piklist Version: 0.10 Beta 3

PHP Version: 5.6.33

Server OS: MacOS 10.13.4

### What was expected to happen
Reactivated an old WIP that was running Piklist 0.9.5x. Updated WordPress to 4.9.5 and Piklist to latest GitHub Beta. The Piklist update notice appeared. Clicked Update Now. Expected it to update the database. 

### What happened instead
The message "Active Plugin Versions Updated..." appeared and then nothing else. An error message was written to the log file: 

[16-Apr-2018 05:46:24 UTC] WordPress database error Table 'wpbrego_wp.wp_post_relationships' doesn't exist for query SELECT post_id, has_post_id FROM wp_post_relationships made by do_action('wp_ajax_piklist_update_0_9_9'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, Piklist_Update_0_9_9->ajax

### Steps to reproduce this
In my local dev environment, this is completely repeatable with that site. Tried theme 2015, all plugins disabled. Activate Piklist and the above happens every time. (Have not seen it on any other sites.) 

I cloned the site to an account on my VPS and there is no problem there. I've tried every variation I can think of but cannot reproduce the failure on a public system. 

I've attached a zip of the WordPress database (MySQL) in case that is helpful: 
[wpbrego_wp.sql.zip](https://github.com/piklist/piklist/files/1914048/wpbrego_wp.sql.zip)

**Comment by sbruner** [comment]
Hi Donna--

Please try this:

REPLACE THIS: https://github.com/piklist/piklist/blob/develop/parts/updates/0.9.9.php#L157-L180

WITH THIS: https://gist.github.com/sbruner/33d707c1ae621ed35b6d41db55a8809b

Let me know if this works. It's untested so please make sure you have a backup of the db.

**Comment by donnamcmaster** [comment]
Thanks, Steve, that works! The update now gives the expected report of its actions and terminates properly. It is no longer telling me to update. (Ironically, I don't think any Piklist fields had ever been created on this WIP, so there was nothing to update and thus nothing else for me to test.)
