### ISSUE TITLE
Not seeing any fields when viewing Common > Term in Demo Taxonomies.

### ISSUE THREAD

**Issue by sbruner** [piklist/piklist#85]
### Details

Piklist Version:
0.10 Develop

### What was expected to happen

Visit Demos > demo taxonomies > edit a term > click on common term.

you should see stuff

### What happened instead

nothing is there.

**Comment by kevinpmiller** [comment]
I think this is an enhancement? The original post hasn't been created yet so it can be in a relationship.

Some thoughts:

- Force the creation of the original post on a post being created for a relationship.
- Disable the ability to relate if there is no post object present.
- Add a validation message to the field checking for a post object.

**Comment by sbruner** [comment]
I don't remember how but we had it show the default WordPress fields. Check the .org version. 

We need to show the default fields.

**Comment by kevinpmiller** [comment]
Pushed to develop for review

**Comment by sbruner** [comment]
Fixed: https://github.com/piklist/piklist/commit/189cf4d5c4f724b117037bba4bae4ccb31c1c2c1
