### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable in /wp-content/plugins/piklist/includes/class-piklist-form.php on line 2833

### ISSUE THREAD

**Issue by johnvanham** [piklist/piklist#87]
### Details

Piklist Version: Latest commit: https://github.com/piklist/piklist/commit/d9bd182dcd4226ed428ccdf0123dab715105e301

PHP Version: 7.2.4

Server OS: MacOS 10.13.3 running Apache/2.4.33 (Unix)

### What was expected to happen

No PHP warnings in demo pages

### What happened instead

PHP Warning on Piklist demo page and also on forms in my own plugin. These warning are not present on PHP 7.1

### Steps to reproduce this

Goto: /wp-admin/edit.php?post_type=piklist_demo&page=piklist_demo_options

![screen shot 2018-04-24 at 14 57 58](https://user-images.githubusercontent.com/1741936/39191944-ee8a2d08-47cf-11e8-8f89-043a74763386.png)

**Comment by sbruner** [comment]
fixed: https://github.com/piklist/piklist/pull/89
