### ISSUE TITLE
Broke on theme Musik

### ISSUE THREAD

**Issue by mrtaurusp** [piklist/piklist#91]
### Details

Piklist Version: 0.1.0

PHP Version: 7.1

Server OS: CENTOS

### What was expected to happen
My theme broke https://themeforest.net/item/musik-responsive-music-wordpress-theme/12127123?ref=flatfull

### Steps to reproduce this
Could you release the older version of this plugin?

**Comment by sbruner** [comment]
Sorry you had an issue with the latest version of Piklist. Can you provide more details?

Can you turn on wp_debug, and post the errors you are receiving here?
https://codex.wordpress.org/WP_DEBUG

**Comment by mrtaurusp** [comment]
I think there are issues with theme provider. They already updated to compatible with Piklist 0.9.9. I've downloaded older version from GitHub and it works well. Thanks for quick response to the issue.

**Comment by sbruner** [comment]
Great. Thanks for letting us know.
