### ISSUE TITLE
Upload file field only allows removal of one at a time.

### ISSUE THREAD

**Issue by sbruner** [piklist/piklist#94]
### Details

Piklist Version:
0.11.1

PHP Version:
7.2

### What was expected to happen
-delete multiple uploaded images.

### What happened instead
-can only delete one at a time.

### Steps to reproduce this
-add new Piklist demo
-on the COMMON > BASICS tab use MEDIA UPLOADER to add a few images.
-save
-now try to remove them. You can only press "-" on one at a time.

<img width="634" alt="screenshot 2018-05-14 17 27 47" src="https://user-images.githubusercontent.com/154488/40024447-52bca6bc-579c-11e8-8b4d-247504b639bb.png">

**Comment by JasonTheAdams** [comment]
@sbruner I'm confused, I thought you could only ever click on one at a time? Do you mean that if you try to remove multiple and save, only one is removed?

**Comment by sbruner** [comment]
@JasonTheAdams this is how it worked in 0.9.9.12:
https://cloudup.com/c8I1zoAW2rT

**Comment by JasonTheAdams** [comment]
@sbruner Right, so now if you delete two what happens? Does the second "-" not work when you click on it? Does it go away but come back when you save?

**Comment by sbruner** [comment]
Fixed: https://github.com/piklist/piklist/pull/97
