### ISSUE TITLE
nested status in register post_type causes 404 pages

### ISSUE THREAD

**Issue by donnamcmaster** [piklist/piklist#95]
### Details

Piklist Version: 0.11.1

PHP Version: 5.6 and 7.2

Server OS: Mac OS 10.13.4 and CENTOS 6.9

### What was expected to happen

- updated Piklist from 0.9.9.16 to 0.11.1; expected site to continue working normally

### What happened instead

- pages all display 404 errors; see https://pik.redpup.net/ for example

### Steps to reproduce this

I was able to distill it to a nested status field when registering post_type via `piklist_post_types` filter. Just install the attached plugin, Register to Kill (`mcpik-register-kill`), on a site running Piklist 0.11.1 and activate it. 

Maybe related to https://github.com/piklist/piklist/issues/69?

I was able to reproduce this on two different sites and 3 themes (one running Twenty Fifteen). The only plugins that need to be running are Piklist and Register to Kill. 

If you want access to the pik.redpup.net site, let me know. But I don't think you'll need it to reproduce this. 

[mcpik-register-kill.zip](https://github.com/piklist/piklist/files/2024825/mcpik-register-kill.zip)

**Comment by sbruner** [comment]
@donnamcmaster Piklist v0.11.2 should fix this issue. Going to close.
